export const KAI51_CONFIG={
  name:"HAxBRO AI Model",
  modelId:"haxbro-ai-model",
  sourceModel:"HuggingFaceTB/SmolLM2-360M-Instruct",
  modelLicense:"Apache-2.0",
  modelRevision:"kai51-model-latest",
  modelHost:"https://github.com/m85948190-ctrl/haxbro/releases/download/kai51-model-latest",
  localModelPath:"/models/kai51/",
  allowRemoteModels:true,
  allowLocalModels:true,
  useBrowserCache:true,
  cacheKey:"haxbro-kai51-v2",
  deviceOrder:["webgpu","wasm"],
  dtypeWebGPU:"q4f16",
  dtypeWasm:"q4",
  generation:{max_new_tokens:64,temperature:0.35,do_sample:false,return_full_text:false},
  context:{maxMessages:3,maxCharsPerMessage:700,maxPromptChars:2200},
  noMultiAgentSwarm:true,
  architecture:"single-core-orchestrator"
};
